=== Myrtanim/xsd2so/Assets/Example/IncludedXSD/XData/main.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
  <xs:include schemaLocation="other.xsd"/>

  <!-- Root element -->
  <xs:element name="buildings" type="buildingsType"/>

  <!-- Root element type -->
  <xs:complexType name="buildingsType">
    <xs:sequence>
      <xs:element type="buildingType" name="building" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="buildingType">
    <xs:sequence>
      <xs:element type="stageType" name="stage" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute type="xs:int" name="id"/>
    <xs:attribute type="xs:string" name="name"/>
    <xs:attribute type="buffHierarchyType" name="hierarchyType" />
  </xs:complexType>

  <xs:complexType name="stageType">
    <xs:sequence>
      <xs:element type="xs:string" name="constrLimit"/>
      <xs:element type="xs:int" name="constrCost"/>
    </xs:sequence>
    <xs:attribute type="xs:int" name="level"/>
    <xs:attribute type="xs:boolean" name="buyable"/>
  </xs:complexType>
</xs:schema>

=== Myrtanim/xsd2so/Assets/Example/IncludedXSD/XData/data.xml
<?xml version="1.0" encoding="utf-8"?>
<buildings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="main.xsd">
  <building id="4" name="mainFarmFence" hierarchyType="PLAYER">
    <stage level="1" buyable="0">
      <constrLimit>Test 1A</constrLimit>
      <constrCost>1</constrCost>
    </stage>
    <stage level="2" buyable="0">
      <constrLimit>Test 1B</constrLimit>
      <constrCost>2</constrCost>
    </stage>
  </building>
  <building id="5" name="gate" hierarchyType="FARM">
    <stage level="1" buyable="0">
      <constrLimit>Test 2A</constrLimit>
      <constrCost>3</constrCost>
    </stage>
    <stage level="2" buyable="0">
      <constrLimit>Test 2B</constrLimit>
      <constrCost>4</constrCost>
    </stage>
  </building>
</buildings>
