=== Myrtanim/xsd2so/Assets/Example/VenetianBlindTest1/XData/venetian_blind_test_1.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.myrtanim.de"
           xmlns="http://www.myrtanim.de"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified">

  <!--
    Notes to this XSD example:
      - is in Venetian Blind style
      - has enumerations
      - has usage of required and optional attributes with and without default values
      - uses elements with text contet
      - uses type inheritance (baseAnimal -> herbivor/carnivor)
  -->
  
  <xs:element name="root" type="rootType"/>

  <xs:simpleType name="plantTypes">
    <xs:restriction base="xs:string">
      <xs:enumeration value="roots" />
      <xs:enumeration value="trees" />
      <xs:enumeration value="herbs" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="sizeCategory">
    <xs:restriction base="xs:string">
      <xs:enumeration value="fine" />
      <xs:enumeration value="diminutive" />
      <xs:enumeration value="tiny" />
      <xs:enumeration value="small" />
      <xs:enumeration value="medium" />
      <xs:enumeration value="large" />
      <xs:enumeration value="huge" />
      <xs:enumeration value="gargantuan" />
      <xs:enumeration value="colossal" />
    </xs:restriction>
  </xs:simpleType>
  
  <xs:complexType name="rootType">
    <xs:sequence>
      <xs:element name="version" type="versionData"/>
      <xs:element name="animals" type="animalDefinitions"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="versionData">
    <xs:sequence>
      <xs:element name="date" type="xs:dateTime" />
      <xs:element name="major" type="xs:int" />
      <xs:element name="minor" type="xs:int" />
      <xs:element name="fix" type="xs:int" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="animalDefinitions">
    <xs:choice minOccurs="1" maxOccurs="unbounded">
      <xs:element name="herbivor" type="herbivorType" />
      <xs:element name="carnivor" type="carnivorType" />
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="baseAnimal">
    <xs:sequence>
      <xs:element name="description" type="xs:string"/>
      <xs:element name="attributeLevels" type="attributeLevels"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="size" type="sizeCategory"/>
  </xs:complexType>
  
  <xs:complexType name="herbivorType">
    <xs:complexContent>
      <xs:extension base="baseAnimal">
        <xs:attribute name="favoritePlantType" type="plantTypes" default="herbs" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="carnivorType">
    <xs:complexContent>
      <xs:extension base="baseAnimal">
        <xs:attribute name="favoriteHerbivor" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="attributeLevels">
    <xs:sequence>
      <xs:element name="level" type="attributeLevel" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="attributeLevel">
    <xs:attribute name="level" type="xs:int" use="required"/>
    <xs:attribute name="strength" type="xs:byte" use="required"/>
    <xs:attribute name="speed" type="xs:byte" use="required"/>
    <xs:attribute name="hitPoints" type="xs:int" use="required"/>
    <xs:attribute name="canFly" type="xs:boolean" default="false"/>
  </xs:complexType>
</xs:schema>

=== Myrtanim/xsd2so/Assets/Example/XData/venetian_blind_test_1.xml
<?xml version="1.0" encoding="utf-8" ?>

<root  xmlns="http://www.myrtanim.de"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.myrtanim.de venetian_blind_test_1.xsd">
  <version>
    <date>2016-07-23T22:25:33</date>
    <major>1</major>
    <minor>0</minor>
    <fix>0</fix>
  </version>
  <animals>
    <carnivor name="Tiger" size="medium" favoriteHerbivor="Wildebeest">
      <description>A big cat.</description>
      <attributeLevels>
        <level level="1" strength="2" speed="4" hitPoints="5" />
        <level level="2" strength="4" speed="4" hitPoints="10" canFly="false"/>
        <level level="3" strength="8" speed="5" hitPoints="20" />
        <level level="4" strength="12" speed="5" hitPoints="30" canFly="true" />
      </attributeLevels>
    </carnivor>
    <herbivor name="Wildebeest" size="large" favoritePlantType="herbs">
      <description>A dumb thing with mean horns.</description>
      <attributeLevels>
        <level level="1" strength="3" speed="2" hitPoints="3" />
        <level level="2" strength="5" speed="3" hitPoints="10"/>
        <level level="3" strength="10" speed="4" hitPoints="30" />
        <level level="4" strength="15" speed="3" hitPoints="50" />
      </attributeLevels>
    </herbivor>
    <carnivor name="Crocodile" size="large" favoriteHerbivor="Wildebeest">
      <description>A Panzerechse.</description>
      <attributeLevels>
        <level level="1" strength="4" speed="3" hitPoints="10" />
        <level level="2" strength="6" speed="5" hitPoints="20" />
        <level level="3" strength="15" speed="6" hitPoints="30" />
        <level level="4" strength="20" speed="4" hitPoints="40" />
      </attributeLevels>
    </carnivor>
  </animals>
</root>
